general {
    colors = true
    interval = 1
}

order += "ipv6"
order += "ethernet eth0"
order += "path_exists VPN"
order += "volume master"
order += "load"
order += "time"

volume master {
    format = "vol.: %volume"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

ethernet eth0 {
    format_up = "eth0: %ip (%speed)"
    format_down = "eth0: down"
}

time {
    format = "%Y-%m-%d %H:%M:%S"
}

load {
    format = "%1min"
    max_threshold = 2
}

path_exists VPN {
    path = "/proc/sys/net/ipv4/conf/tun0"
}
