general {
    colors = true
    interval = 1
}

order += "wireless wlp0s0f3"
order += "ethernet enp0s20f0u1u4"
order += "path_exists wg-maineuwest3"
order += "path_exists wg-meucentral1"
order += "battery 0"
order += "volume master"
order += "load"
order += "time"

volume master {
    format = "vol.: %volume"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

wireless wlp0s0f3 {
    format_up = "wlp: %ip (%quality at %essid, %bitrate)"
    format_down = "wlp: down"
}

ethernet enp0s20f0u1u4 {
    format_up = "eth: %ip"
    format_down = "eth: down"
}

battery 0 {
    format = "bat.: %percentage (%remaining)"
    low_threshold = 30
    threshold_type = time
}

time {
    format = "%Y-%m-%d %H:%M:%S"
}

load {
    format = "%1min"
    max_threshold = 2
}

path_exists wg-maineuwest3 {
    path = "/proc/sys/net/ipv4/conf/wg-maineuwest3"
    format = "main-eu-west-3"
}

path_exists wg-meucentral1 {
    path = "/proc/sys/net/ipv4/conf/wg-meucentral1"
    format = "main-eu-central-1"
}
