#!/usr/bin/env php
<?php
/*
 * Run adminer and show it in firefox.
 */

exit(main());

function main()
{
    if (version_compare(PHP_VERSION, '5.4', '<')) {
        throw new \RuntimeException('PHP ≥ 5.4 is required.');
    }

    $cacheDir = getCacheDirPath();
    prepareCache($cacheDir, [
        'index.php'   => 'http://adminer.org/latest-en.php',
        'adminer.css' => 'https://raw.github.com/vrana/adminer/master/designs/hever/adminer.css',
    ]);

    $port = 8083;
    if (serverIsRunning($port)) {
        return 0;
    }

    runServer($cacheDir, $port);
    launchBrowser($port);

    return 0;
}

function launchBrowser($port)
{
    $host = "localhost:$port";
    exec('firefox -remote "ping()" > /dev/null 2>&1', $_, $running);
    if ($running === 0) {
        exec("firefox -remote 'openurl(http://$host/, new-tab)' > /dev/null 2>&1 &");
    } else {
        exec("firefox 'http://$host/' > /dev/null 2>&1 &");
    }
}

/**
 * @param int $port
 */
function runServer($cacheDir, $port)
{
    exec(sprintf(
        "cd %s && setsid php -S localhost:%s > /dev/null 2>&1 &",
        escapeshellarg($cacheDir),
        (int) $port
    ));
}

/// @return bool true if adminer is already being served.
function serverIsRunning($port)
{
    exec(
        sprintf(
            "netstat -plant 2> /dev/null | grep -E ':$port*php'",
            (int) $port
        ),
        $_,
        $exit
    );
    return $exit === 0;
}

/// @return string path to cache directory.
function getCacheDirPath()
{
    $home = posix_getpwuid(posix_getuid())['dir'];
    return "$home/.cache/adminer";
}

/**
 * Create and populate cache if needed.
 *
 * @param string $cacheDir path to cache directory.
 * @param string[] $downloads {dest: url}
 */
function prepareCache($cacheDir, $downloads)
{
    if (!file_exists($cacheDir)) {
        if (mkdir($cacheDir) !== true) {
            throw new \RuntimeException("Could not create cache directory: `$cacheDir`.");
        }
    }

    if (!is_dir($cacheDir)) {
        throw new \RuntimeException("Cache directory is not a folder: `$cacheDir`.");
    }

    if (!is_writable($cacheDir)) {
        throw new \RuntimeException("Can't write to cache directory: `$cacheDir`.");
    }

    foreach ($downloads as $destName => $url) {
        $dest = "$cacheDir/$destName";

        if (!file_exists($dest)) {
            $contents = file_get_contents($url);
            if ($contents === false) {
                throw new \RuntimeException("Unable to download `$url`.");
            }

            $written = file_put_contents($dest, $contents);

            if ($written !== strlen($contents)) {
                throw new \RuntimeException("Unable to write to `$dest`.");
            }
        }
    }
}
