#!/usr/bin/env php
<?php declare(strict_types=1);

exit(main());

function main(): int
{
    echo 'Daily: ';
    print_left(7.8 * 3600);

    echo 'Weekly: ';
    $fdow = strtotime('last sunday');
    $ldow = strtotime('next saturday');
    $range = date('Y-m-d H:i:s', $fdow) . '-' . date('Y-m-d', $ldow);
    print_left(5 * 7.8 * 3600, $range);

    return 0;
}

function print_left(float $allocated, string $range = '')
{
    $delta = $allocated - get_total($range);
    $abs = intval(time() + $delta);
    $abs -= $abs % 60;

    if ($delta <= 0) {
        $delta *= -1;
        echo '-';
    }

    $h = intval($delta / 3600);
    $m = intval($delta / 60) % 60;

    printf("%dh %dm (%s)\n", $h, $m, date('H:i:s', $abs));
}

function get_total($range = '')
{
    if (strlen($range) > 0) {
        $range = escapeshellarg($range);
    }

    $entries = array_filter(array_map('trim', explode(
        "\n",
        shell_exec(sprintf(
            'hamster-cli list %s | tail -n +3 | cut -d"(" -f2 | cut -d")" -f1',
            $range
        ))
    )));

    $total = 0;
    foreach (array_map('parse_entry', $entries) as $v) {
        list($h, $m) = $v;
        $total += ($h * 3600) + ($m * 60);
    }

    return $total;
}

function parse_entry(string $str): array
{
    $h = 0;
    $m = 0;

    foreach (array_map('trim', explode(' ', $str)) as $v) {
        $d = intval(preg_replace('`[^\d]`', '', $v));
        if ($v[strlen($v) - 1] === 'h') {
            $h = $d;
        } else {
            $m = $d;
        }
    }

    return[$h, $m];
}
