#!/usr/bin/env sh
export DISPLAY=:0
dunst &
sleep 2
xsetroot -solid black &
gtk-redshift -l manual &
setxkbmap 'fr(oss)'
xrandr --output DisplayPort-1 --primary --mode 1920x1080 --rate 144
sleep 1
xwallpaper --no-randr --center "$HOME/.background.png" &
